version: 2

sources:
  - name: staging
    # for bigquery it's a dataset but it's the same of a database
    database: dtc-de-course-431213
    schema: trips_data_all

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
